# Generated by Django 4.1.1 on 2022-12-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='world',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CONTINENT', models.CharField(max_length=100)),
                ('COUNTRY', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Park',
        ),
    ]
