# Generated by Django 4.1.1 on 2022-12-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_world_delete_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='co',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='world',
            name='pi',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='world',
            name='ve',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
