# Generated by Django 4.1.1 on 2022-12-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_world_co_world_pi_world_ve'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='H1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='world',
            name='H2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='world',
            name='H3',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
