# Generated by Django 4.1.1 on 2022-12-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_world_h1_world_h2_world_h3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='world',
            old_name='H1',
            new_name='p1',
        ),
        migrations.RenameField(
            model_name='world',
            old_name='H2',
            new_name='p2',
        ),
        migrations.RenameField(
            model_name='world',
            old_name='H3',
            new_name='p3',
        ),
        migrations.RenameField(
            model_name='world',
            old_name='co',
            new_name='p4',
        ),
        migrations.RenameField(
            model_name='world',
            old_name='pi',
            new_name='p5',
        ),
        migrations.RenameField(
            model_name='world',
            old_name='ve',
            new_name='p6',
        ),
    ]
